image:
  name: python:3.7-slim

stages:
- test
- publish

before_script:
- pip install -r requirements-dev.txt
- python setup.py install

test:
  stage: test
  script:
  - pytest

publish:
  only:
  - master
  stage: publish
  script:
  - rm -rf dist/
  - ls -la
  - pip install twine wheel
  - python setup.py sdist bdist_wheel
  - twine upload --repository-url https://upload.pypi.org/legacy/ dist/kubeobject-*
