image:
  name: python:3.7-slim

stages:
- test
- publish

before_script:
- pip install -r requirements-test.txt
- python setup.py install

test:
  tags:
  - kubeobject
  stage: test
  script:
  - pytest

publish:
  only:
  - tags
  stage: publish
  script:
  - pip install twine wheel
  - python setup.py sdist bdist_wheel
  - twine upload dist/kubeobject-*
