---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dummies.kubeobject.com
spec:
  group: kubeobject.com
  version: v1
  scope: Namespaced
  names:
    kind: Dummy
    plural: dummies
    shortnames:
    - dum
    singular: dummy
